referenceGenome: "38"

locus: "chr1:50000-51000"

loci:
  - chr1
  - chr2


samplesInfo:
  
  samples:
    3sample:
      spliceJunctions_bed: gs://macarthurlab-rnaseq/test_data/3sample.SJ.out.tab.bed.gz
      coverage_bigWig: gs://macarthurlab-rnaseq/test_data/3sample.bigWig

    2sample:
      spliceJunctions_bed: gs://macarthurlab-rnaseq/test_data/2sample.SJ.out.tab.bed.gz
      coverage_bigWig: gs://macarthurlab-rnaseq/test_data/2sample.bigWig

    sampleA:
      spliceJunctions_bed: gs://macarthurlab-rnaseq/test_data/sampleA.SJ.out.tab.bed.gz
      coverage_bigWig: gs://macarthurlab-rnaseq/test_data/sampleA.bigWig

    sampleB:
      spliceJunctions_bed: gs://macarthurlab-rnaseq/test_data/sampleB.SJ.out.tab.bed.gz
      coverage_bigWig: gs://macarthurlab-rnaseq/test_data/sampleB.bigWig

    sampleC:
      spliceJunctions_bed: gs://macarthurlab-rnaseq/test_data/sampleC.SJ.out.tab.bed.gz
      coverage_bigWig: gs://macarthurlab-rnaseq/test_data/sampleC.bigWig


      